FROM amazoncorretto:17-alpine
COPY target/registration-login-demo-0.0.1-SNAPSHOT.jar usr/app/registration-login-demo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/usr/app/registration-login-demo-0.0.1-SNAPSHOT.jar"]